package dns

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/cilo/cilo/pkg/models"
)

// RenderConfig generates a complete dnsmasq configuration from the current state.
// It includes system resolver detection and all environment/service DNS entries.
func RenderConfig(state *models.State) (string, error) {
	var sb strings.Builder

	// Header with generation timestamp
	sb.WriteString("# Auto-generated by cilo\n")
	sb.WriteString("# DO NOT EDIT MANUALLY\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))

	// Core dnsmasq settings
	sb.WriteString("port=5354\n")
	sb.WriteString("bind-interfaces\n")
	sb.WriteString("listen-address=127.0.0.1\n\n")

	// Upstream DNS servers (detected from system)
	upstreams := getSystemUpstreams()
	if len(upstreams) == 0 {
		upstreams = []string{"8.8.8.8"}
	}
	sb.WriteString("# Upstream DNS (detected from system)\n")
	for _, upstream := range upstreams {
		sb.WriteString(fmt.Sprintf("server=%s\n", upstream))
	}
	sb.WriteString("\n")

	// Environment and service DNS entries
	if state != nil && len(state.Environments) > 0 {
		sb.WriteString("# Environment services\n")
		for envKey, env := range state.Environments {
			if env == nil || len(env.Services) == 0 {
				continue
			}

			sb.WriteString(fmt.Sprintf("# Environment: %s\n", envKey))

			// Generate address entries for each service
			for _, svc := range env.Services {
				if svc == nil || svc.IP == "" {
					continue
				}

				suffix := env.DNSSuffix
				if suffix == "" {
					suffix = ".test"
				}

				// Service-specific hostname
				hostname := fmt.Sprintf("%s.%s%s", svc.Name, env.Name, suffix)
				sb.WriteString(fmt.Sprintf("address=/%s/%s\n", hostname, svc.IP))

				// Additional hostnames from service config
				for _, customHostname := range svc.Hostnames {
					sb.WriteString(fmt.Sprintf("address=/%s/%s\n", customHostname, svc.IP))
				}

				// Wildcard and apex entries for ingress services
				if svc.IsIngress {
					// Wildcard: *.project.envname.test
					wildcardHostname := fmt.Sprintf(".%s.%s%s", env.Project, env.Name, suffix)
					sb.WriteString(fmt.Sprintf("address=/%s/%s\n", wildcardHostname, svc.IP))

					// Apex: project.envname.test
					apexHostname := fmt.Sprintf("%s.%s%s", env.Project, env.Name, suffix)
					sb.WriteString(fmt.Sprintf("address=/%s/%s\n", apexHostname, svc.IP))
				}
			}
			sb.WriteString("\n")
		}
	}

	return sb.String(), nil
}

// getSystemUpstreams detects system DNS servers based on the operating system.
// For Linux, it checks systemd-resolved first, then /etc/resolv.conf.
// For macOS, it uses scutil --dns.
// Returns a list of upstream DNS servers, or empty if detection fails.
func getSystemUpstreams() []string {
	switch runtime.GOOS {
	case "linux":
		return getLinuxUpstreams()
	case "darwin":
		return getMacOSUpstreams()
	default:
		return []string{}
	}
}

// getLinuxUpstreams detects DNS servers on Linux systems.
// Checks /run/systemd/resolve/resolv.conf first (systemd-resolved),
// then falls back to /etc/resolv.conf.
func getLinuxUpstreams() []string {
	// Try systemd-resolved first
	if upstreams := parseResolvConf("/run/systemd/resolve/resolv.conf"); len(upstreams) > 0 {
		return upstreams
	}

	// Fall back to /etc/resolv.conf
	if upstreams := parseResolvConf("/etc/resolv.conf"); len(upstreams) > 0 {
		return upstreams
	}

	return []string{}
}

// parseResolvConf reads a resolv.conf file and extracts nameserver entries.
// Skips 127.0.0.53 (systemd-resolved stub resolver).
func parseResolvConf(path string) []string {
	file, err := os.Open(path)
	if err != nil {
		return []string{}
	}
	defer file.Close()

	var upstreams []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Skip comments and empty lines
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse nameserver entries
		if strings.HasPrefix(line, "nameserver") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				ns := parts[1]
				// Skip systemd-resolved stub resolver
				if ns != "127.0.0.53" {
					upstreams = append(upstreams, ns)
				}
			}
		}
	}

	return upstreams
}

// getMacOSUpstreams detects DNS servers on macOS using scutil.
func getMacOSUpstreams() []string {
	cmd := exec.Command("scutil", "--dns")
	output, err := cmd.Output()
	if err != nil {
		return []string{}
	}

	var upstreams []string
	scanner := bufio.NewScanner(strings.NewReader(string(output)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Look for nameserver entries in scutil output
		if strings.HasPrefix(line, "nameserver[") {
			// Format: "nameserver[0] : 8.8.8.8"
			parts := strings.Split(line, ":")
			if len(parts) >= 2 {
				ns := strings.TrimSpace(parts[1])
				if ns != "" && ns != "127.0.0.1" {
					upstreams = append(upstreams, ns)
				}
			}
		}
	}

	return upstreams
}
