// Copyright (c) 2026 Cilo Authors
// SPDX-License-Identifier: MIT
// See LICENSES/MIT.txt for full license text

package dns

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/sharedco/cilo/internal/models"
)

func RenderConfig(state *models.State) (string, error) {
	var sb strings.Builder

	sb.WriteString("# Auto-generated by cilo\n")
	sb.WriteString("# DO NOT EDIT MANUALLY\n")
	sb.WriteString(fmt.Sprintf("# Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))

	sb.WriteString("port=5354\n")
	sb.WriteString("bind-interfaces\n")
	sb.WriteString("listen-address=127.0.0.1\n")
	if u := os.Getenv("SUDO_USER"); u != "" {
		sb.WriteString(fmt.Sprintf("user=%s\n", u))
	}
	sb.WriteString("\n")

	upstreams := getSystemUpstreams()
	if len(upstreams) == 0 {
		upstreams = []string{"8.8.8.8"}
	}
	sb.WriteString("# Upstream DNS (detected from system)\n")
	for _, upstream := range upstreams {
		sb.WriteString(fmt.Sprintf("server=%s\n", upstream))
	}
	sb.WriteString("\n")

	entries, _ := RenderEntries(state)
	sb.WriteString(entries)

	return sb.String(), nil
}

func RenderEntries(state *models.State) (string, error) {
	var sb strings.Builder

	if state != nil && len(state.Hosts) > 0 {
		sb.WriteString("# Environment services\n")
		for hostID, host := range state.Hosts {
			if len(host.Environments) > 0 {
				sb.WriteString(fmt.Sprintf("# Host: %s\n", hostID))

				for envKey, env := range host.Environments {
					if env == nil || len(env.Services) == 0 {
						continue
					}

					sb.WriteString(fmt.Sprintf("# Environment: %s\n", envKey))

					for _, svc := range env.Services {
						if svc == nil || svc.IP == "" {
							continue
						}

						suffix := env.DNSSuffix
						if suffix == "" {
							suffix = ".test"
						}

						hostname := fmt.Sprintf("%s.%s%s", svc.Name, env.Name, suffix)
						sb.WriteString(fmt.Sprintf("address=/%s/%s\n", hostname, svc.IP))

						for _, customHostname := range svc.Hostnames {
							sb.WriteString(fmt.Sprintf("address=/%s/%s\n", customHostname, svc.IP))
						}

						if svc.IsIngress {
							wildcardHostname := fmt.Sprintf(".%s.%s%s", env.Project, env.Name, suffix)
							sb.WriteString(fmt.Sprintf("address=/%s/%s\n", wildcardHostname, svc.IP))

							apexHostname := fmt.Sprintf("%s.%s%s", env.Project, env.Name, suffix)
							sb.WriteString(fmt.Sprintf("address=/%s/%s\n", apexHostname, svc.IP))
						}
					}
					sb.WriteString("\n")
				}
			}
		}
	}

	return sb.String(), nil
}

func getSystemUpstreams() []string {
	switch runtime.GOOS {
	case "linux":
		return getLinuxUpstreams()
	case "darwin":
		return getMacOSUpstreams()
	default:
		return []string{}
	}
}

func getLinuxUpstreams() []string {
	if upstreams := parseResolvConf("/run/systemd/resolve/resolv.conf"); len(upstreams) > 0 {
		return upstreams
	}

	if upstreams := parseResolvConf("/etc/resolv.conf"); len(upstreams) > 0 {
		return upstreams
	}

	return []string{}
}

func parseResolvConf(path string) []string {
	file, err := os.Open(path)
	if err != nil {
		return []string{}
	}
	defer file.Close()

	var upstreams []string
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		if strings.HasPrefix(line, "nameserver") {
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				ns := parts[1]
				if ns != "127.0.0.53" {
					upstreams = append(upstreams, ns)
				}
			}
		}
	}

	return upstreams
}

func getMacOSUpstreams() []string {
	cmd := exec.Command("scutil", "--dns")
	output, err := cmd.Output()
	if err != nil {
		return []string{}
	}

	seen := make(map[string]bool)
	var upstreams []string
	scanner := bufio.NewScanner(strings.NewReader(string(output)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if strings.HasPrefix(line, "nameserver[") {
			parts := strings.SplitN(line, " : ", 2)
			if len(parts) < 2 {
				continue
			}
			ns := strings.TrimSpace(parts[1])
			if ns == "" || ns == "127.0.0.1" || strings.Contains(ns, ":") || seen[ns] {
				continue
			}
			seen[ns] = true
			upstreams = append(upstreams, ns)
		}
	}

	return upstreams
}
