name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. cilo init
        2. cilo create myapp ...
        3. cilo up myapp
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please provide logs from the command that failed.
      render: bash
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS version, Docker version, Cilo version.
      placeholder: |
        - OS: Ubuntu 22.04
        - Docker: 24.0.5
        - Cilo: 0.2.1
